runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /javascript
  static_dir: javascript
- url: /stylesheets
  static_dir: stylesheets
- url: /aboutus
  static_dir: aboutus
- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
